-- Throwaway Supabase project ONLY. Never run this against QWeb's or the personal site's database.
drop table if exists events, sponsors cascade;
create table events (
  id bigint generated by default as identity primary key,
  title text not null,
  starts_at timestamptz,
  capacity int,
  published boolean default false,
  meta jsonb,
  updated_at timestamptz not null default now()
);
create table sponsors (
  id bigint generated by default as identity primary key,
  name text not null,
  tier text
);
create or replace function touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;
create trigger events_touch before update on events for each row execute function touch_updated_at();
alter publication supabase_realtime add table events, sponsors;
insert into events (title, starts_at, capacity, published) values
  ('Tutorial 1', '2026-09-17 18:00-04', 60, true),
  ('Tutorial 2', '2026-09-24 18:00-04', 60, false);
insert into sponsors (name, tier) values ('Acme', 'gold'), ('Globex', 'silver');
